### ISSUE TITLE
UnknownError: Connection refused 

### ISSUE THREAD

**Issue by anthonygreen** [hacklschorsch/selenium-webdriverjs#2]
Attempting to use selenium-webdriverjs with Cucumber.js 

https://github.com/anthonygreen/hsmp.js

I'm getting the error

UnknownError: Connection refused
    at new bot.Error (./node_modules/selenium-webdriverjs/webdriver/lib/atoms/error.js:92:18)
    at Object.bot.response.checkResponse (./node_modules/selenium-webdriverjs/webdriver/lib/atoms/response.js:106:9)
    at ./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/webdriver.js:136:24
    at ./node_modules/selenium-webdriverjs/webdriver/lib/goog/base.js:1112:15
    at webdriver.promise.Application.runInNewFrame_ (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/promise.js:1308:20)
    at notify (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/promise.js:299:24)
    at notifyAll (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/promise.js:274:7)
    at resolve (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/promise.js:369:7)
    at ./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/promise.js:539:51
    at ./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/http/http.js:97:5
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/webdriver.js:133:61)
    at Function.webdriver.WebDriver.createSession (./node_modules/selenium-webdriverjs/webdriver/lib/webdriver/webdriver.js:112:30)
    at node.Builder.build (./node_modules/selenium-webdriverjs/webdriver/lib/node/builder.js:45:32)
    at new World (./features/support/world.js:10:40)
    at Object.instantiateNewWorld (/usr/local/share/npm/lib/node_modules/cucumber/lib/cucumber/support_code/library.js:54:19)
    at Object.visitScenario (/usr/local/share/npm/lib/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:43:26)
    at self.instructVisitorToVisitScenarios (/usr/local/share/npm/lib/node_modules/cucumber/lib/cucumber/ast/feature.js:80:17)
    at processItem (/usr/local/share/npm/lib/node_modules/cucumber/lib/cucumber/type/collection.js:19:9)
    at iterate (/usr/local/share/npm/lib/node_modules/cucumber/lib/cucumber/type/collection.js:12:11)

**Comment by erichjrusch** [comment]
Same issue.  How did you manage to fix this?
